# Additional Option for When condition
#  ansible_network_os == * 
---
- name: Update config of a Cisco switch.
  include_tasks: ios.yml
  when: "'cisco' in {{ group_names }}"

- name: Update config of a Juniper switch.
  include_tasks: junos.yml
  when: "'juniper' in {{ group_names }}"

- name: Update config of an Arista switch.
  include_tasks: eos.yml
  when: "'arista' in {{ group_names }}"

- name: Update config of an Aruba switch.
  include_tasks: arubaos.yml
  when: "'aruba' in {{ group_names }}"
