# https://www.rogerperkin.co.uk/network-automation/ansible/cisco-ios-upgrade-for-switch/
- name: CHECK CURRENT VERSION
  ios_facts:

- debug:
    msg:
    - "Current version is {{ ansible_net_version }}"
    - "Upgrade image is {{ upgrade_version }}"
 
- name: Exit if {{ upgrade_version }} is found
    msg:
    - "Image is  compliant and will be upgraded"
  when: ansible_net_version == upgrade_ios_version
  meta: end_play

- name: Copy Image // This could take up to 4 minutes
  net_put:
    src: "{{ upgrade_filepath }}"
    dest: "flash:/{{ upgrade_filename }}"

- name: Change Boot Variable to new image 
  ios_config:
    commands:
      - "boot system flash:{{ upgrade_filename }}"
    save_when: always

- name: Reload the Device 
  cli_command:
    command: reload
    prompt:
      - confirm
    answer:
      - 'y'
